### ISSUE TITLE
The addon doesn't load on 1.18.2!

### ISSUE THREAD

**Issue by G4stavoM1ster** [Apeiros-46B/AlchimiaVitae#5]
## Steps to reproduce the Issue (Required)
Step 1: Download the latest version of the addon.
Step 2: Put the .jar on your server plugins folder.
Step 3: Download the latest Paper 1.18.2 build.
Step 4: Start the server and see what happens.

## Expected behavior (Required)
The addon working, but sadly, it's doesn't work.

## Server Log / Error Report
`[21:22:30 ERROR]: Could not load 'plugins\SlimefunAlchimiaVitae.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage$Builder net.kyori.adventure.text.minimessage.MiniMessage$Builder.removeDefaultTransformations()'
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[purpur-1.18.2.jar:git-Purpur-1585]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1585]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1585]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1585]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage$Builder net.kyori.adventure.text.minimessage.MiniMessage$Builder.removeDefaultTransformations()'
        at me.apeiros.alchimiavitae.AlchimiaVitae.<clinit>(AlchimiaVitae.java:15) ~[SlimefunAlchimiaVitae.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more`

**Comment by Apeiros-46B** [comment]
This should be fixed in the latest build (wait a while for it to appear, it probably won't appear immediately), let me know if it still doesn't work
FYI the newest version requires java 17 and paper 1.18.2
